#!/bin/bash

declare -r nodeVersion=6.3.0

declare -r dockerImage=mhart/alpine-node:${nodeVersion}
declare -r volumeOrigin=`pwd`
declare -r volumeDestine=/tmp
declare -r containerName='read-storybook'

docker rm -f ${containerName} >> /dev/null 2>&1

docker run \
    -it \
    -v ${volumeOrigin}:${volumeDestine} \
    -p 9001:9001 \
    --name ${containerName} \
    ${dockerImage} sh -c "cd ${volumeDestine} && npm run storybook"
